### PR TITLE
2.0-preview

### LINKED ISSUE #61: Polymer 2?
Has this element (or all the Gold elements for that concern) been deprecated?
If not will they be upgraded to Polymer 2?
I don't see any branch letting me suppose so at the moment

### PR DESCRIPTION
**Pull request by e111077**
fixes #61.

changes without whitespace -> [here](https://github.com/PolymerElements/gold-cc-expiration-input/pull/63/files?w=1)

### CODE REVIEW

**Comment by e111077** [comment]
Travis is failing because `wct -s` is not defined? Tests seem to pass otherwise

@azakus any idea as to why that's happening? I basically copied the `travis.yml` from `iron-ajax`

**Comment by e111077** [comment]
ping @notwaldorf @bicknellr @valdrinkoshi @cdata

**Comment by notwaldorf** [comment]
Looking! what's up with the tests?

**Comment by notwaldorf** [comment]
LGTM! (if you take a look at those tests!) :shipit:

**Pull request merged**
