### PR TITLE
Fixed compute value

### PR DESCRIPTION
**Pull request by andrew-silva-movile**

### CODE REVIEW

**Comment by notwaldorf** [comment]
Why is this needed? With multi property observers, you get notified when _either_ of the arguments changes

**Comment by notwaldorf** [comment]
Also, please add a description or link to a bug or something, so that we can understand what the PR is trying to fix :)

**Comment by andrew-silva-movile** [comment]
Hi @notwaldorf, sorry I commented in the issue (Bug #53) but not here.

**Comment by notwaldorf** [comment]
@andrew-silva-movile tests are super grumpy :(

**Comment by andrew-silva-movile** [comment]
@notwaldorf about multi property observers, I created because `_computeDate` observer is just fired when `month` and `year` are defined, so as we start defining the `month` I never got `value` changed.

"Observers are not invoked until all dependent properties are defined (!== undefined)"
https://www.polymer-project.org/1.0/docs/devguide/observers

But I'm trying to pre-define `month` and `year`, as documentation explan :smiley:
"So each dependent properties should have a default value defined in properties (or otherwise be initialized to a non-undefined value) to ensure the observer is called."

**Comment by andrew-silva-movile** [comment]
@notwaldorf  I improved keeping only one observer, but ensuring that observer is always called (no undefined values). o/

About tests I don't know why I'm getting assert error, I'm not acquainted with JS tests process (I should), but I'm investigating.

Do not give up on me. :laughing:

**Comment by notwaldorf** [comment]
Not giving up! Let me know if you get stuck! 🍰

**Comment by andrew-silva-movile** [comment]
Thanks @notwaldorf !
Now tests are super happy! :smile: 

The last change I did was compute `value` before bind `month` and `year` inside `date-input`. It was necessary to not replace `value` firing `dateChanged` without correct `month` and `year` (`_computedMonth` and `_computedYear`).

**Comment by notwaldorf** [comment]
Awesome, thanks so much!

**Pull request merged**
